name: MY
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Add your additional steps here
